### ISSUE TITLE
AxonOps not working with Java 17 - which is the default with Cassandra 5.0-beta1

### ISSUE THREAD

**Issue by arodrime** [rustyrazorblade/easy-cass-lab#150]
To get AxonOps to work with Cassandra 5.0 (beta), I had to select Java 11 as follows:

```
$ sudo update-alternatives --config java
There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-17-openjdk-amd64/bin/java      1711      auto mode
  1            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      manual mode
* 2            /usr/lib/jvm/java-17-openjdk-amd64/bin/java      1711      manual mode
  3            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
```

It was confirmed to me by AxonOps team that they only support Java 11. In case we use Cassandra 5+ it is understandable that we would like to run Java 17, AxonOps agent will also come to accept Java 17 eventually.

In the meantime, I don't know if the best is to enforce Java 11 for both (I did this for now, it works and is good enough for me), or to make sure that Cassandra uses Java 17 while AxonOps agent sticks to Java 11, so to differentiate Java versions of the 2 components which is maybe a more accurate fix, but maybe a bit harder.

**Comment by rustyrazorblade** [comment]
I'm testing out a patch for #28 now and should have it pushed up today.  Pretty straightfoward.

**Comment by rustyrazorblade** [comment]
Another thing... you can also push up cassandra_versions.yaml to the boxes using SCP, because `use-cassandra` references that when you pick your version.  So you don't even have to rebuild the image, just copy the file up.

**Comment by rustyrazorblade** [comment]
#28 has been merged, which allows you to override the Java version.  You'll need to rebuild the packer image as it updates the `use-cassandra` script that's set up when the AMI is built.
