### ISSUE TITLE
Support editable configuration 

### ISSUE THREAD

**Issue by rustyrazorblade** [rustyrazorblade/easy-cass-lab#17]
I think as part of the `use` command we should download the entire conf directory to the local directory so it can be edited.

Seeds should be populated automatically.

What's a reasonable way to have the config be edited then pushed up with the node specific variables substituted?  Maybe when it's uploaded we pull the yaml into easy-cass-lab, set the listen address and then send it the modified version to the node.

In the working directory for the cluster, I'm thinking we have a `conf/<version>` directories, that get populated via the `easy-cass-lab pull-configs` command.

`easy-cass-lab push-configs` to push everything up.

**Comment by rustyrazorblade** [comment]
Looking into how to simplify this by allowing a user to supply a small patch file, and apply it using `yq` server side.

**Comment by rustyrazorblade** [comment]
Automatically add the seed and listen address info to the yaml when applying the patch.

**Comment by rustyrazorblade** [comment]
UX question... should this keep rolling changes forward, or always apply to the original base yaml?    I think it should always apply the patch to the original, meaning we need to create a copy of the original during the packer phase and `cp cassandra.yaml cassandra.yaml.original` for each version we set up.

**Comment by jrwest** [comment]
I had originally assumed that it would apply to whatever YAML was there but thinking about it now that you bring it up I like your approach better. That way you keep appending to your patch file and you have all your changes in one place instead of spread over many patch files.

**Comment by rustyrazorblade** [comment]
I should have this done tomorrow or Wednesday.

**Comment by rustyrazorblade** [comment]
A bunch of this work is pushed up now.  The ability to upload files, generate a new config with `write-config`, and `update-config` with the alias `uc`.

**Comment by rustyrazorblade** [comment]
I still need to deal with jvm.options / jvm-server.options, the behavior changed in 4.0.
