### ISSUE TITLE
Could not find com.avast.gradle:gradle-docker-compose-plugin:0.9.4

### ISSUE THREAD

**Issue by minho95** [rustyrazorblade/easy-cass-lab#199]
I am trying to clone the repo and build it locally, however when running `./gradlew shadowJar installdist` I run into:

```
AILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'easy-cass-lab'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.avast.gradle:gradle-docker-compose-plugin:0.9.4.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/0.9.4/gradle-docker-compose-plugin-0.9.4.pom
       - https://plugins.gradle.org/m2/com/avast/gradle/gradle-docker-compose-plugin/0.9.4/gradle-docker-compose-plugin-0.9.4.pom
     Required by:
         project :
```

I went to https://repo.maven.apache.org/maven2/com/avast/gradle/gradle-docker-compose-plugin/ and I see that there is no version 0.9.4 anymore. Should this be updated?

When I tried to include listed version my build failed on:
```
* What went wrong:
java.lang.UnsupportedClassVersionError: com/bmuschko/gradle/docker/DockerRemoteApiPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> com/bmuschko/gradle/docker/DockerRemoteApiPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

I have also tried without success: https://stackoverflow.com/questions/57688507/how-to-fix-plugin-was-not-found-in-any-of-the-following-sources

Output of `java -version`:
```
openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment (build 17.0.12+7-Ubuntu-1ubuntu222.04)
OpenJDK 64-Bit Server VM (build 17.0.12+7-Ubuntu-1ubuntu222.04, mixed mode, sharing)
```

**Comment by rustyrazorblade** [comment]
Thanks for reporting this, I must have had it sitting in my Gradle cache for a while.

I initially was going to bump the version, but I took a deeper look and this isn't actually used anywhere, so I've removed it.  At one point there was a more complex build process that used docker compose, but it's not part of the repo anymore.
