### ISSUE TITLE
install python

### ISSUE THREAD

**Issue by rustyrazorblade** [rustyrazorblade/easy-cass-lab#29]
Looks like python isn't installed, I think the packages are python2 and python3.  I'm not sure what happens if both are installed and someone types cqlsh.  Might need to do the same thing I did for java, picking a current version, but we'll see.

**Comment by jrwest** [comment]
Steps:


1. Add pyenv to ami
2. add need python versions to ami via pyenv
3. add python versions to `cassandra_versions.yaml` 
4. modify use-cassandra to switch between python versions via pyenv

**Comment by jrwest** [comment]
Steps 1 & 2 added in `5907810c0eb33451ed77c2b0d0b87cd95fdbeaad`

**Comment by jrwest** [comment]
Steps 3 & 4 added in `48cfc74d8247d5a95830577abf35cfb9532ff2d1`. Closing.
