### ISSUE TITLE
Support EBS

### ISSUE THREAD

**Issue by rustyrazorblade** [rustyrazorblade/easy-cass-lab#50]
we should be able to specify EBS volumes

https://registry.terraform.io/providers/aaronfeng/aws/latest/docs/resources/ebs_volume
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/volume_attachment

**Comment by rustyrazorblade** [comment]
I think the flags should go under a high level `ebs` option, like `--ebs.type gp2`, `--ebs.iop 3000`.  

This can do on the `init`

```
    enum class EbsTypes(val n: String)
    {
        NONE(""),
        GP2("gp2"),
  
    }
    @Parameter(names = ["--ebs.type"])
    var ebsType = EbsTypes.NONE
```

which gives us nice validation:
```
❯ easy-cass-lab init --ebs.type boo
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" com.beust.jcommander.ParameterException: Invalid value for --ebs.type parameter. Allowed values:[NONE, GP2]
```

Would be nice to support every type of EBS

**Comment by jrwest** [comment]
Added in https://github.com/rustyrazorblade/easy-cass-lab/pull/102
